Repository HisteriaMC/HisteriaPack, pull requests merged in 2023-10, with the labels that each got.

#22 Objets liés aux bosses
  attachables/ares_chestplate.json
  attachables/hades_crown.json
  attachables/hermes_sandals.json
  textures/items/ares_chestplate.png
  textures/items/boss_key.png
  textures/items/dionysus_chalice.png
  textures/items/hades_crown.png
  textures/items/hermes_sandals.png
  textures/items/histerite_totem.png
  textures/models/armor/ares_chestplate_1.png
  textures/models/armor/hades_crown_1.png
  textures/models/armor/hermes_sandals_1.png
Labels: enhancement, high priority

#31 histerite anvil et box
  models/blocks/box.geo.json
  models/blocks/histerite_anvil.geo.json
  textures/blocks/box.png
  textures/blocks/histerite_anvil.png
Labels: enhancement, high priority

#21 Add low fire
  textures/blocks/fire_0.png
  textures/blocks/fire_1.png
Labels: enhancement, high priority

#81 Changement textures items (Vague 1)
  textures/items/banknote.png
  textures/items/hammer.png
  textures/items/histerite_apple.png
  textures/items/histerite_compress.png
  textures/items/histerite_core.png
  textures/items/histerite_stick.png
  textures/items/lottery_ticket.png
  textures/items/nocturite_compress.png
  textures/items/nocturite_core.png
  textures/items/punching_ball.png
Labels: enhancement, high priority

#10 Feature/custom blocks
  textures/blocks/drawer_side.png
  textures/blocks/drawer_top.png
  textures/blocks/emerald_block.png
  textures/blocks/emerald_ore.png
  textures/blocks/endframe_front.png
  textures/blocks/endframe_side.png
  textures/blocks/endframe_top.png
  textures/blocks/fertilized_dirt.png
  textures/blocks/flipbook_textures.json
  textures/blocks/glowing_obsidian.png
  textures/blocks/histerite_block.png
  textures/blocks/histerite_ore.png
  textures/blocks/lapis_ore.png
  textures/blocks/nether_wart_block.png
  textures/blocks/nocturite_block.png
  textures/blocks/poisonous_obsidian.png
  textures/blocks/random_ore.png
  textures/blocks/reactor_core_stage_0.png
  textures/blocks/reinforced_obsidian.png
  textures/blocks/soul_sand-1.png
  textures/blocks/soul_sand-2.png
  textures/blocks/soul_sand.png
  textures/blocks/sponge.png
  textures/flipbook_textures.json
  textures/terrain_texture.json
Labels: enhancement, high priority

#87 Items (Phase 2)
  textures/items/chest_explorer.png
  textures/items/chest_finder.png
  textures/items/forge_note.png
  textures/items/histerite_axe.png
  textures/items/histerite_hoe.png
  textures/items/histerite_pickaxe.png
  textures/items/histerite_shovel.png
  textures/items/histerite_sword.png
  textures/items/nether_wart.png
  textures/items/nocturite_crystal.png
  textures/items/nocturite_seed.png
Labels: enhancement, medium priority

#100 Sound, Particles and Scoreboard
  font/glyph_E1.png
  particles/blood_particle.json
  particles/corrupt_particle.json
  particles/dark_flame_particle.json
  particles/histerite_totem_particle.json
  particles/lift_particle.json
  particles/red_critical_particle.json
  particles/sweep_particle.json
  sounds/random/blood_hit.ogg
  sounds/random/blood_hit2.ogg
  sounds/random/execution1.ogg
  sounds/random/execution2.ogg
  sounds/random/lift1.ogg
  sounds/random/lift2.ogg
  sounds/random/lyre.ogg
  sounds/sound_definitions.json
  textures/particle/blood.png
  textures/particle/corrupt.png
  textures/particle/lift.png
  textures/particle/sweep.png
  textures/ui/Black_sb.json
  textures/ui/Black_sb.png
  textures/ui/logo_scoreboard.png
  textures/ui/title.png
  ui/_global_variables.json
  ui/pause_screen.json
  ui/scoreboards.json
  ui/settings_sections/general_section.json
  ui/settings_sections/world_section.json
Labels: enhancement, high priority

#103 Nocturite & Histerite Chest
  models/entity/chest.geo.json
  textures/blocks/histerite_chest.png
  textures/blocks/nocturite_chest.png
Labels: enhancement, high priority

#105 Histerite totem (Changement sous la demande d'Ailfe)
  textures/items/histerite_totem.png
Labels: enhancement, high priority

#101 Nocturite Armor
  textures/items/nocturite_boots.png
  textures/items/nocturite_boots.tga
  textures/items/nocturite_chestplate.png
  textures/items/nocturite_chestplate.tga
  textures/items/nocturite_helmet.png
  textures/items/nocturite_helmet.tga
  textures/items/nocturite_leggings.png
  textures/items/nocturite_leggings.tga
  textures/models/armor/nocturite_1.png
  textures/models/armor/nocturite_2.png
Labels: enhancement, high priority, MVP

#113 Emojis + Geometry fix
  attachables/lotus_staff.entity.json
  attachables/spear.entity.json
  attachables/trident.entity.json
  font/glyph_E1.png
  models/entity/lotus_staff.geo.json
  models/entity/spear.geo.json
Labels: enhancement, high priority, MVP

#115 Fix neon block animation
  textures/flipbook_textures.json
Labels: enhancement, medium priority

#110 Nocturite Plant
  models/blocks/nocturite_plant.geo.json
  textures/blocks/nether_wart_stage_0.png
  textures/blocks/nether_wart_stage_1.png
  textures/blocks/nether_wart_stage_2.png
  textures/blocks/nocturite_plant_stage_0.png
  textures/blocks/nocturite_plant_stage_1.png
  textures/blocks/nocturite_plant_stage_2.png
  textures/blocks/nocturite_plant_stage_3.png
Labels: enhancement, high priority, MVP

#109 Spike
  entity/spike.entity.json
  models/blocks/spike.geo.json
  models/entity/spike.geo.json
  models/mobs.json
  textures/blocks/spike.png
  textures/entity/skeleton.png
  textures/entity/skulls/skeleton.png
Labels: enhancement, high priority, MVP

#108 Cobble Breaker
  textures/blocks/cobble_breaker_bottom.png
  textures/blocks/cobble_breaker_side.png
  textures/blocks/cobble_breaker_top.png
Labels: enhancement, high priority

#92 Items (Vague 4)
  models/entity/dynamite.geo.json
  models/entity/lotus_staff.geo.json
  models/entity/spear.geo.json
  textures/entity/dynamite.png
  textures/entity/lotus_staff.png
  textures/entity/spear.png
  textures/items/dynamite.png
  textures/items/egg.png
  textures/items/histerite_core.png
  textures/items/hood.png
  textures/items/lotus_staff.png
  textures/items/magic_lyre.png
  textures/items/obsidian_breaker.png
  textures/items/shuriken.png
  textures/items/spear.png
  textures/items/thunderbolt.png
  textures/items/tpstick.png
  textures/models/armor/hood_helmet_1.png
Labels: enhancement, high priority

#111 item (vague 5)
  textures/items/jump_stick.png
  textures/items/speed_stick.png
Labels: enhancement, high priority, MVP

#107 Items (Vague 3)
  textures/items/emerald.png
  textures/items/histerite_ingot.png
  textures/items/nocturite_fruit.png
Labels: enhancement, low priority

#117 Added back Obsidian Breaker
  textures/items/obsidian_breaker.png
Labels: bug, high priority

#124 Rota chest (Noc et Hist)
  models/entity/chest.geo.json
Labels: bug, high priority

#127 Fix de la rotation de l'Histerite Anvil
  models/blocks/histerite_anvil.geo.json
Labels: bug, high priority

#128 Custom Entities
  animations/attachables/dynamite.animation.json
  attachables/dynamite.json
  attachables/shuriken.json
  entity/grapling_hook.json
  models/entity/dynamite.geo.json
  models/entity/grapling_hook.geo.json
  textures/entity/grapling_hook.png
Labels: enhancement, high priority, MVP

#129 Texte pour les items/blocks ainsi qu'UI
  texts/en_UK.lang
  texts/en_US.lang
  texts/fr_CA.lang
  texts/fr_FR.lang
Labels: enhancement, high priority
